---
- name: Locales, Timezone, and Keyboard - List available console keymaps
  tags: get-console-keymap
  shell: "nlsadm list-console-keymap"
  become: yes
  become_user: root
  register: LocalesTimezoneKeyboard_ListAvailableConsoleKeymaps_output

- debug:
    var: LocalesTimezoneKeyboard_ListAvailableConsoleKeymaps_output.stdout