---
- hosts: all
  name: Test
  tasks:
    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
      copy:
        content: hello world
        dest: /tmp/testfile.txt

- hosts: node1
  roles:
    - role: System_Configuration_Configure_hostname
      vars:
          hostname: "myhost"
    - role: System_Configuration_SetNameserver_SMF
      vars: 
          nameserver: "192.168.1.1"
          domain: "mydomain.internal"
          nameservice_switch: "files dns"
    - role: System_Configuration_SetNameserver_nscfg
     