---
- hosts: node1
  roles:
    # - role: SystemConfiguration_ConfigureHostname
    #   hostname: "myhost"
    # - role: SystemConfiguration_SetNameserverSMF
    #   nameserver: "192.168.1.1"
    #   domain: "mydomain.internal"
    #   nameservice_switch: "files dns"
    # - role: SystemConfiguration_SetNameserverNscfgImport
    #   resolv_conf_file: "/Users/joergmoellenkamp/solaris114cheatsheet/testcase_files/resolv.conf.1"
    #   nsswitch_conf_file: "/Users/joergmoellenkamp/solaris114cheatsheet/testcase_files/resolv.conf.1"      
    # - role: LocalesTimezoneKeyboard_InstallNlsadm
    # - role: LocalesTimezoneKeyboard_GetCurrentConfiguration
    # - role: LocalesTimezoneKeyboard_ListAvailableTimezones
    # - role: LocalesTimezoneKeyboard_ListAvailableConsoleKeymaps
    # - role: LocalesTimezoneKeyboard_ListAvailableLocales
    # - role: LocalesTimezoneKeyboard_SetTimezone
    #   timezone: "Europe/Berlin"
    # - role: LocalesTimezoneKeyboard_SetLocale
    #   locale: "de_DE.UTF-8"
    # - role: LocalesTimezoneKeyboard_SetConsoleKeymap 
    #   console_keymap: "UK-English"
    # - role: UsersAndRoles_RootAsUser 
    # - role: UsersAndRoles_RootAsRole 
    # - role: UsersAndRoles_RootRoleWithUserPassword 
    # - role: UsersAndRoles_SetRoleAuth  
    #   roleauth: role
    #   rolename: root
    # - role: UsersAndRoles_RootRoleWithRolePassword 
    # - role: UsersAndRoles_AddUserWithProfile
    #   profile: "System Administrator"
    #   username: "joerg1"
    # - role: UsersAndRoles_DeleteUser 
    #   username: "joerg1"
    # - role: UsersAndRoles_CreateUserGeneric 
    #   username_generic: "joerg2"
    #   hostname_generic: "localhost"
    # - role: UsersAndRoles_DeleteUser 
    #   username: "joerg2"
    # - role: UsersAndRoles_CreateUserLocal 
    #   username: "joerg3"
    # - role: UsersAndRoles_DeleteUser 
    #   username: "joerg3"    
    # - role: UsersAndRoles_CreateUserNFS 
    #   username: "joerg4"
    #   hostname: "localhost"
    # - role: UsersAndRoles_DeleteUser 
    #   username: "joerg4"  
    # - role: BootEnvironments_ListBE 
    # - role: BootEnvironments_CreateBE 
    #   BootEnvironmentName: solaris-05032012
    # - role: BootEnvironments_ActivateBE 
    #   BootEnvironmentName: solaris-05032012
    # - role: BootEnvironments_ActivateBE 
    #   BootEnvironmentName: solaris-1
    # - role: BootEnvironments_DestroyBE
    #   BootEnvironmentName: solaris-05032012  
    # - role: Packaging_InstallPackage 
    #   PackageName: "diagnostic/wireshark"
    # - role: Packaging_ShowPackageInfo 
    #   PackageName: "wireshark"
    # - role: Packaging_ShowPackageContents
    #   PackageName: "wireshark" 
    # - role: Packaging_InstallPackage 
    #   PackageName: "solaris-desktop"    
    # - role: Packaging_UninstallPackage 
    #   PackageName: "diagnostic/wireshark"
    # - role: Packaging_UninstallPackage 
    #   PackageName: "solaris-desktop"
    # - role: Packaging_UpdateSystem 
    # - role: Packaging_ListAvailablePackages 
    # - role: Packaging_UpdateSystemDryRun 
    # - role: Packaging_ListInstalledPackages 
    # - role: Packaging_PackageSearch 
    #   SearchFor: "math.h"
    # - role: Packaging_DependencySearch 
    #   PackageName: "library/libxml2"
    # - role: Packaging_ShowPublisher 
    - role: Packaging_ConfigureSRUUpdates 
      SRUCertificate: /Users/joergmoellenkamp/solaris114cheatsheet/keys/pkg.oracle.com.certificate.pem
      SRUKey: /Users/joergmoellenkamp/solaris114cheatsheet/keys/pkg.oracle.com.key.pem