---
- name: UsersAndRoles_SetRoleAuth
  shell: rolemod -K roleauth={{ roleauth }} {{ rolename }}
  become: yes
  become_user: root
  register: UsersAndRoles_SetRoleAuth_output

- debug:
    var: UsersAndRoles_SetRoleAuth_output.stdout